use_frameworks!

target 'PXStickyHeaderCollectionView_Example' do
  pod 'PXStickyHeaderCollectionView', :path => '../'

  target 'PXStickyHeaderCollectionView_Tests' do
    inherit! :search_paths
  end
end
