source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.0'

target 'PXStickyHeaderCollectionView_Example' do
  pod 'PXStickyHeaderCollectionView', :path => '../'
  pod 'PureLayout'
end
